# Generated by Django 4.1.4 on 2022-12-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=90)),
                ("byline", models.CharField(max_length=20)),
                ("introduction", models.TextField(max_length=300)),
                ("body", models.TextField(max_length=300)),
                ("conclusion", models.TextField(max_length=300)),
            ],
        ),
    ]
