# Generated by Django 4.1.4 on 2022-12-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="body",
            field=models.TextField(
                default="this is the body of your article", max_length=1500
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="byline",
            field=models.CharField(default="write author name here", max_length=100),
        ),
        migrations.AlterField(
            model_name="article",
            name="conclusion",
            field=models.TextField(default="conclude your article", max_length=1500),
        ),
        migrations.AlterField(
            model_name="article",
            name="headline",
            field=models.CharField(default="Enter headline here", max_length=200),
        ),
        migrations.AlterField(
            model_name="article",
            name="introduction",
            field=models.TextField(default="write intro here", max_length=1500),
        ),
    ]
