# Generated by Django 4.1.4 on 2022-12-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_alter_article_body_alter_article_byline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(default="", max_length=254, upload_to=""),
            preserve_default=False,
        ),
    ]
